[package]
name = "rspc"
description = "A blazing fast and easy to use TRPC server for Rust."
version = "0.1.3"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition = "2021"
license = "MIT"
include = ["/src", "/LICENCE", "/README.md"]
repository = "https://github.com/oscartbeaumont/rspc"
documentation = "https://docs.rs/rspc/latest/rspc"
keywords = ["async", "specta", "rust-to-ts", "typescript", "typesafe"]
categories = ["web-programming", "asynchronous"]

[features]
default = []
tauri = ["dep:tauri"]
tracing = ["dep:tracing"]
httpz = ["dep:httpz", "httpz/cookies"]
# openapi = ["dep:openapiv3"]
anyhow = ["dep:anyhow"]

# Webservers
axum = ["httpz", "httpz/axum", "httpz/tokio-ws", "httpz/axum"]
# actix-web = ["httpz/actix-web"]
# poem = ["httpz/poem"]
# rocket = ["httpz/rocket"]
# warp = ["httpz/warp"]
# TODO: Following ones are exposed but not officially supported
lambda = ["httpz", "httpz/lambda", "httpz/ws", "httpz/axum"]
workers = ["httpz", "httpz/workers", "httpz/ws"]
vercel = ["httpz", "httpz/vercel", "httpz/ws", "axum"]

# Specta
uuid = ["specta/uuid"]
chrono = ["specta/chrono"]
time = ["specta/time"]
bigdecimal = ["specta/bigdecimal"]
rust_decimal = ["specta/rust_decimal"]
indexmap = ["specta/indexmap"]
ipnetwork = ["specta/ipnetwork"]
mac_address = ["specta/mac_address"]
bit-vec = ["specta/bit-vec"]
bson = ["specta/bson"]
uhlc = ["specta/uhlc"]
bytesize = ["specta/bytesize"]
glam = ["specta/glam"]

[dependencies]
specta = { version = "1.0.0", features = ["serde", "typescript", "tokio"] }
httpz = { version = "0.0.4", optional = true } # TODO: Move back to crates.io release
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
thiserror = "1.0.38"
futures = "0.3.26"
tokio = { version = "1.26.0", features = ["sync", "rt", "macros"] }
tauri = { version = "1.2.4", optional = true }
tracing = { version = "0.1.37", optional = true }
worker = { version = "0.0.12", optional = true }
anyhow = { version = "1", optional = true }
futures-locks = { git = "https://github.com/oscartbeaumont/futures-locks", rev = "a2e880337e6bfb3140a261932667149607e3ada9", features = ["tokio"] }
futures-channel = "0.3.27"
nougat = "0.2.4"

[dev-dependencies]
async-stream = "0.3.4"

[workspace]
members = [
    "./create-rspc-app",
    "./examples",
    "./examples/axum",
    "./examples/vercel",
]

[patch.crates-io]
httpz = { git = "https://github.com/oscartbeaumont/httpz", rev = "be67ead9320095bdecf90cae75fded2411509b0f" } # TODO: Move back to crates.io release