[package]
name = "rspc"
description = "A blazingly fast and easy to use TRPC server for Rust."
version = "0.1.2"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition = "2021"
license = "MIT"
include = ["/src", "/LICENCE", "/README.md"]
repository = "https://github.com/oscartbeaumont/rspc"
documentation = "https://docs.rs/rspc/latest/rspc"
keywords = ["async", "specta", "rust-to-ts", "typescript", "typesafe"]
categories = ["web-programming", "asynchronous"]

[features]
default = []
tauri = ["dep:tauri"]
tracing = ["dep:tracing"]
httpz = ["dep:httpz", "httpz/cookies"]
openapi = ["dep:openapiv3", "dep:httpz", "dep:include_dir", "dep:mime_guess", "specta/openapi"]
# playground = []

# Webservers # Axum feature basically always enabled because we use the extractors regardless of webserver
axum = ["httpz/axum", "httpz/tokio-ws", "httpz/axum"]
actix-web = ["httpz/actix-web", "httpz/tokio-ws", "httpz/axum"]
# poem = ["httpz/poem"]
rocket = ["httpz/rocket", "httpz/tokio-ws", "httpz/axum"]
# warp = ["httpz/warp"]
lambda = ["httpz/lambda", "httpz/ws", "httpz/axum"]
workers = ["httpz/workers", "httpz/ws"]

# Specta
uuid = ["specta/uuid"]
chrono = ["specta/chrono"]
time = ["specta/time"]
bigdecimal = ["specta/bigdecimal"]
rust_decimal = ["specta/rust_decimal"]
indexmap = ["specta/indexmap"]
ipnetwork = ["specta/ipnetwork"]
mac_address = ["specta/mac_address"]
bit-vec = ["specta/bit-vec"]
bson = ["specta/bson"]
uhlc = ["specta/uhlc"]

[dependencies]
specta = { version = "0.0.4", path = "./crates/specta", features = ["serde"] }
httpz = { git = "https://github.com/oscartbeaumont/httpz.git", rev = "1ddbd9ad594ac7ee3e5b167afe689d1ce1228519", optional = true } # TODO: Move back to crates.io release
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
thiserror = "1.0.37"
futures = "0.3.25"
tokio = { version = "1.21.2", features = ["sync", "rt", "macros"] }
tauri = { version = "1.2.1", optional = true }
tracing = { version = "0.1.37", optional = true }
async-stream = "0.3.3"
openapiv3 = { version = "1.0.1", optional = true }
include_dir = { version = "0.7.3", optional = true, features = ["metadata"] }
mime_guess = { version = "2.0.4", optional = true }
worker = { version = "0.0.11", optional = true }

[dev-dependencies]
async-stream = "0.3.3"

[workspace]
members = [
  "./crates/normi",
  "./crates/normi/macros",
  "./crates/specta",
  "./crates/specta/macros",
  "./create-rspc-app",
  "./examples",
  "./examples/axum",
]
