[package]
name = "example-axum"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
rspc = { path = "../../", features = ["axum"] }
tokio = { version = "1.29.1", features = ["full"] }
async-stream = "0.3.5"
axum = { version = "0.6.19", features = ["ws"] }
tower-http = { version = "0.4.1", default-features = false, features = ["cors"] }
futures = "0.3.28"
