[package]
name = "example-axum"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
rspc = { path = "../../", features = ["axum", "alpha"] }
tokio = { version = "1.27.0", features = ["full"] }
async-stream = "0.3.4"
axum = { version = "0.6.12", features = ["ws"] }
tower-http = { version = "0.4.0", default-features = false, features = ["cors"] }
