[package]
name = "example-axum"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
rspc = { path = "../../", features = ["tracing", "unstable"] }
rspc-httpz = { path = "../../crates/httpz", features = ["axum"] }
tokio = { version = "1.33.0", features = ["full"] }
async-stream = "0.3.5"
axum = { version = "0.6.20", features = ["ws", "http2"] }
tower-http = { version = "0.4.4", default-features = false, features = ["cors"] }
futures = "0.3.28"
tracing = "0.1.40"
tracing-subscriber = "0.3.17"
thiserror = { workspace = true }
serde = { workspace = true }
specta = { workspace = true }
