[package]
name = "rspc-example-tauri"
version = "0.0.0"
edition = "2021"
publish = false

[build-dependencies]
tauri-build = { version = "1.4", features = [] }

[dependencies]
tauri = { version = "1.4", features = ["shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rspc = { path = "../../../", features = ["unstable"] }
rspc-tauri = { path = "../../../crates/tauri" }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
async-stream = "0.3.5"
futures = "0.3.28"
specta = { workspace = true }
thiserror = { workspace = true }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
