[package]
name = "normi-macros"
description = "Macros for Normi"
version = "0.0.1"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/oscartbeaumont/rspc/tree/main/crates/normi"
readme = "README.md"
documentation = "https://docs.rs/normi"
keywords = ["async", "rspc", "normalised-cache", "typescript", "typesafe"]
categories = ["web-programming", "asynchronous"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.47"
quote = "1.0.21"
syn = "1.0.103"
