[package]
name = "rspc-tauri"
version = "1.0.0-rc.5"
edition = "2021"

[dependencies] # TODO: Typescript support should be optional
futures = "0.3.28"
rspc-core = { version = "1.0.0-rc.5", path = "../core", default-features = false, features = [
    "typescript",
    "tokio",
] } # TODO: Avoid tokio and typescript features
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.107"
tauri = { version = "1.4.1", default-features = false, features = ["wry"] } # TODO: Work without wry
tauri-specta = { git = "https://github.com/oscartbeaumont/tauri-specta", rev = "1073c8da4e4fccbeebfb389b2f093ac711cd35df", default-features = false, features = [
    "typescript",
] }
specta = { workspace = true }
