[package]
name = "example"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
rspc = { path = "../", features = ["axum", "openapi"] }
async-stream = "0.3.3"
axum = "0.6.1"
chrono = { version = "0.4.23", features = ["serde"] }
serde = { version = "1.0.152", features = ["derive"] }
time = "0.3.17"
tokio = { version = "1.23.1", features = ["rt-multi-thread", "macros", "time", "sync"], default-features = false }
tower-cookies = "0.8.0"
tower-http = { version = "0.3.5", default-features = false, features = ["cors"] }
uuid = { version = "1.2.2", features = ["v4", "serde"] }
serde_json = "1.0.91"
