[package]
name = "example"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
rspc = { path = "../", features = ["axum"] }
async-stream = "0.3.5"
axum = "0.6.19"
chrono = { version = "0.4.26", features = ["serde"] }
serde = { version = "1.0.171", features = ["derive"] }
time = "0.3.23"
tokio = { version = "1.29.1", features = ["rt-multi-thread", "macros", "time", "sync"], default-features = false }
tower-cookies = "0.9.0"
tower-http = { version = "0.4.1", default-features = false, features = ["cors"] }
uuid = { version = "1.4.1", features = ["v4", "serde"] }
serde_json = "1.0.103"
specta = "1.0.4"
