[package]
name = "example"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
rspc = { path = "../", features = [] }
rspc-httpz = { path = "../crates/httpz", features = ["axum"] }
async-stream = "0.3.5"
axum = "0.6.20"
chrono = { version = "0.4.31", features = ["serde"] }
serde = { version = "1.0.188", features = ["derive"] }
time = "0.3.29"
tokio = { version = "1.32.0", features = ["rt-multi-thread", "macros", "time", "sync"], default-features = false }
tower-cookies = "0.9.0"
tower-http = { version = "0.4.4", default-features = false, features = ["cors"] }
uuid = { version = "1.4.1", features = ["v4", "serde"] }
serde_json = "1.0.107"
specta = { workspace = true }
thiserror = { workspace = true }
