[package]
name = "example"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
rspc = { path = "../", features = ["axum"] }
async-stream = "0.3.4"
axum = "0.6.12"
chrono = { version = "0.4.24", features = ["serde"] }
serde = { version = "1.0.159", features = ["derive"] }
time = "0.3.20"
tokio = { version = "1.27.0", features = ["rt-multi-thread", "macros", "time", "sync"], default-features = false }
tower-cookies = "0.9.0"
tower-http = { version = "0.4.0", default-features = false, features = ["cors"] }
uuid = { version = "1.3.0", features = ["v4", "serde"] }
serde_json = "1.0.95"
